# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-15 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20180715_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
